"use client";
import { ArrowRight, Check, CircleAlert, FlaskConical, RefreshCw, ShieldCheck } from "lucide-react";
import type { Evaluation, EvaluationStage, Training } from "@/lib/types";

const percent = (value?: number) => value === undefined ? "—" : `${Math.round(value * 100)}%`;
const roleNames: Record<string, string> = { manager: "Manager", department_head: "Dept. head", finance: "Finance", cfo: "CFO" };

function Scorecard({ stage, trained = false }: { stage?: EvaluationStage; trained?: boolean }) {
  return <article className={`card scorecard ${trained ? "trained" : ""}`}><span className="eyebrow">{trained ? "AFTER FINE-TUNING" : "BEFORE FINE-TUNING"}</span><h2>{trained ? "Your WorkflowDNA model" : "Original River base model"}</h2><div className="score-main"><strong>{stage ? `${stage.metrics.correct}/${stage.metrics.total}` : "—"}</strong><span>exact matches</span>{stage && <span className="score-percent">{percent(stage.metrics.exact_match_accuracy)}</span>}</div><div className="score-details"><div><span>Correct approval routing</span><strong>{percent(stage?.metrics.approval_accuracy)}</strong></div><div><span>Valid structured output</span><strong>{percent(stage?.metrics.valid_json_rate)}</strong></div><div><span>Passes all policy checks</span><strong>{percent(stage?.metrics.policy_guardrail_pass_rate)}</strong></div></div><p>{stage ? "Measured on the same five held-out scenarios." : "No completed evaluation has been recorded yet."}</p></article>;
}

export default function ModelLab({ training, evaluation, refreshing, onRefresh, onTry }: { training: Training; evaluation: Evaluation | null; refreshing: boolean; onRefresh: () => void; onTry: () => void }) {
  const ready = !!training.river.checkpoint && training.river.status === "trained";
  const after = evaluation?.after_checkpoint;
  const results = evaluation?.before?.results || after?.results || [];
  return <>
    <div className="model-banner"><span className="model-banner-icon"><FlaskConical size={26} /></span><div><h2>A custom model. An honest comparison.</h2><p>{training.train_count} synthetic training examples. {training.eval_count} unseen evaluation scenarios. Actual River responses, measured before and after training.</p></div><button className="button secondary" onClick={onRefresh} disabled={refreshing}><RefreshCw size={15} className={refreshing ? "spin" : ""} />Refresh status</button></div>
    <section className="card river-run-card"><div className="model-card-heading"><span className="model-icon river">R</span><div><span className="eyebrow">RIVER AI · SUPERVISED FINE-TUNING</span><h2>{evaluation?.base_model || "Custom reimbursement model"}</h2></div><span className={`state-pill ${ready ? "success" : "warning"}`}>{ready ? <Check size={13} /> : <CircleAlert size={13} />}{training.river.status.replaceAll("_", " ")}</span></div><p>{training.river.message}</p><div className="checkpoint-box"><span>INFERENCE CHECKPOINT · SAVED ON RIVER</span><code>{training.river.checkpoint || "No checkpoint saved yet. Training status above is live."}</code></div><div className="run-stat-row"><span><strong>{training.train_count}</strong> training examples</span><span><strong>{training.eval_count}</strong> held-out examples</span><span><strong>{evaluation?.loss_history?.length ?? "—"}</strong> training updates</span><button className="text-button" onClick={onTry} disabled={!ready}>Try the trained model<ArrowRight size={15} /></button></div></section>
    <div className="score-grid"><Scorecard stage={evaluation?.before} /><Scorecard stage={after} trained /></div>
    <section className="card evaluation-card"><div className="card-heading"><div><h2>Unseen examples, side by side</h2><p>These five scenarios are excluded from the training data.</p></div><span className="source-label">ACTUAL MODEL OUTPUTS</span></div>{results.length ? <div className="evaluation-table-wrap"><table className="evaluation-table"><thead><tr><th>Held-out scenario</th><th>Original model</th><th>Trained checkpoint</th><th>Required outcome</th></tr></thead><tbody>{results.map((before, i) => {
      const trained = after?.results.find(row => row.id === before.id);
      const scenario = before.scenario || trained?.scenario;
      return <tr key={before.id}><td><strong>{scenario ? new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(scenario.amount) : `Scenario ${i + 1}`}</strong><span>{scenario ? scenario.exception ? "Policy exception" : !scenario.receipt_present ? "Missing receipt" : "Standard reimbursement" : before.id}</span></td>{[before, trained].map((result, column) => <td key={column}>{result ? <><span className={`result-badge ${result.exact_match ? "pass" : "fail"}`}>{result.exact_match ? <Check size={12} /> : <CircleAlert size={12} />}{result.exact_match ? "Exact match" : result.valid ? "Mismatch" : "Invalid output"}</span><span>{result.prediction ? result.prediction.required_approvals.map(role => roleNames[role] || role).join(" + ") : result.error || "No valid JSON"}</span>{result.prediction?.review_required && <small>Manual review required</small>}</> : <span>Awaiting evaluation</span>}</td>)}<td><span>{before.expected.required_approvals.map(role => roleNames[role] || role).join(" + ")}</span><small>{before.expected.review_required ? "Retain controls · Human review" : `${before.expected.required_approvals.length} required approvals`}</small></td></tr>;
    })}</tbody></table></div> : <div className="evaluation-empty">{evaluation?.message || "The comparison will appear when River evaluation completes. No results are simulated."}</div>}
    <div className="eval-footnote"><ShieldCheck size={15} /><p>Exact match includes approval order, removals, review status, and policy citations. Five synthetic cases are a demonstration, not evidence of production reliability.</p></div></section>
    {results.length > 0 && <section className="card raw-results"><h2>Inspect the evidence</h2><p>Raw responses are retained, including failures. Expand a case to inspect what each model actually returned.</p>{results.map(row => <details key={row.id}><summary>{row.id}<span>Raw before / after output</span></summary><div className="raw-output-grid"><div><strong>Original model</strong><pre>{typeof row.raw_prediction === "string" ? row.raw_prediction : JSON.stringify(row.raw_prediction, null, 2)}</pre></div><div><strong>Trained checkpoint</strong><pre>{after?.results.find(item => item.id === row.id)?.raw_prediction || "Awaiting evaluation"}</pre></div></div></details>)}</section>}
    <section className="card run-instructions"><div><h2>Reproduce the River training run</h2><p>Activate the project’s Python environment. Credentials stay in the root .env file.</p></div><div><span>Train and evaluate</span><code>python -m training.train_river --epochs 3 --batch-size 4</code></div><p>The model uses River’s official completion-only SFT loop. The checkpoint manifest, loss history, and raw evaluation report are saved under artifacts/. The command uses real River credits.</p><a className="text-button" href="https://docs.river.ai/guides/sft/" target="_blank" rel="noreferrer">Official River SFT documentation<ArrowRight size={15} /></a></section>
  </>;
}
